/**
 * Cleaned excerpt based on app/api/availability/route.ts.
 * The endpoint validates query parameters and delegates slot generation to the availability service.
 */

type AvailabilityRequest = {
  salonSlug?: string | null;
  serviceId?: string | null;
  serviceIds?: string[];
  date?: string | null;
};

export function validateAvailabilityRequest(input: AvailabilityRequest):
  | { ok: true; value: { salonSlug: string; serviceId?: string; serviceIds: string[]; date: string } }
  | { ok: false; reason: string } {
  const serviceIds = input.serviceIds?.filter(Boolean) ?? [];

  if (!input.salonSlug || (!input.serviceId && serviceIds.length === 0) || !input.date) {
    return { ok: false, reason: "salonSlug_service_and_date_required" };
  }

  return {
    ok: true,
    value: {
      salonSlug: input.salonSlug,
      serviceId: input.serviceId ?? undefined,
      serviceIds,
      date: input.date,
    },
  };
}

/**
 * In production this calls getAvailability({ salonSlug, serviceId, serviceIds, date }).
 * Keeping this sample small makes the workflow boundary easier to review.
 */
export async function availabilityEndpoint(input: AvailabilityRequest) {
  const validated = validateAvailabilityRequest(input);

  if (!validated.ok) {
    return { status: 400, body: { error: validated.reason } };
  }

  return {
    status: 200,
    body: {
      slots: "generated by availability service",
      request: validated.value,
    },
  };
}
